name: Check TFC Workspace Existence
description: Determines whether a Terraform Cloud workspace exists
inputs:
  tfcToken:
    description: A Terraform Cloud API token with access to manage the workspace
    required: true
  orgName:
    description: The name of the Terraform Cloud organization where the workspace resides
    required: true
  workspaceName:
    description: The name of the Terraform Cloud workspace
    required: true
runs:
  using: docker
  image: docker://frostedcarbon/tfc-cli:v1.0.0
  args:
    - workspaces
    - show
    - -token
    - ${{ inputs.tfcToken }}
    - -org
    - ${{ inputs.orgName }}
    - -workspace
    - ${{ inputs.workspaceName }}
branding:
  icon: arrow-up-right
  color: blue
